parameters:
  db.connection.driver: pdo_sqlite
  db.connection.path: '%app.basePath%var/db.sqlite'

  orm.paths:
    - '%app.basePath%src/CodeList/Posters/Ports/Resources'
    - '%app.basePath%src/CodeList/Ads/Ports/Resources'
    - '%app.basePath%src/Application/DomainEvents/Ports/Resources'

  em.options:
    connection:
      driver: '%db.connection.driver%'
      path: '%db.connection.path%'
    mappingPaths: '%orm.paths%'
    debug: '%app.debug%'

  log.path: '%app.basePath%var/log/app.log'

services:
  # Controllers
  Ads\UI\Web\Slim\Controllers\SignUpPosterController:
    public: true
    arguments:
    - '@Ads\Application\CommandBus\Bus'
    - '@router'
    - '@Ads\CodeList\Registration\SignUp\SignUpPosterAction'
  Ads\UI\Web\Slim\Controllers\DomainEventsController:
    public: true
    arguments:
    - '@Ads\Application\CommandBus\Bus'
    - '@router'
    - '@Ads\Application\StoredEvents\ViewEventsInPageAction'
  Ads\UI\Web\Slim\Controllers\LoginController:
    public: true
    arguments:
    - '@Ads\Application\CommandBus\Bus'
    - '@router'
    - '@Ads\CodeList\Authentication\Login\LoginAction'
    - '@Ads\UI\Web\HTTP\JWT\TokenFactory'
  Ads\UI\Web\Slim\Controllers\DraftAdController:
    public: true
    arguments:
    - '@Ads\Application\CommandBus\Bus'
    - '@router'
    - '@Ads\CodeList\Listings\DraftAd\DraftAdAction'
  # Actions
  Ads\CodeList\Registration\SignUp\SignUpPosterAction:
    arguments:
    - '@Ads\CodeList\Posters\Posters'
  Ads\Application\StoredEvents\ViewEventsInPageAction:
    arguments:
    - '@Ads\Application\DomainEvents\EventStore'
  Ads\CodeList\Authentication\Login\LoginAction:
    arguments:
    - '@Ads\CodeList\Posters\Posters'
  Ads\CodeList\Listings\DraftAd\DraftAdAction:
    arguments:
    - '@Ads\CodeList\Posters\Posters'
    - '@Ads\CodeList\Ads\Ads'
  # Middleware
  Ads\UI\Web\Slim\Middleware\EventSubscribersMiddleware:
    public: true
    arguments:
    - '@Ads\Application\DomainEvents\StoredEventsSubscriber'
  Ads\UI\Web\Slim\Middleware\RequestLoggerMiddleware:
    public: true
    arguments:
    - '@Psr\Log\LoggerInterface'
  Ads\UI\Web\Slim\Middleware\QueryLoggerMiddleware:
    public: true
    arguments:
    - '@Psr\Log\LoggerInterface'
    - '@Doctrine\ORM\EntityManager'
  Ads\Application\DomainEvents\StoredEventsSubscriber:
    arguments:
    - '@Ads\Application\DomainEvents\EventStore'
    - '@Ads\Application\DomainEvents\StoredEventFactory'
  # Repositories
  Ads\CodeList\Posters\Posters:
    class: 'Ads\CodeList\Posters\Ports\PostersRepository'
    arguments:
      - '@Doctrine\ORM\EntityManager'
  Ads\Application\DomainEvents\EventStore:
    class: 'Ads\Application\DomainEvents\Ports\EventStoreRepository'
    arguments:
      - '@Doctrine\ORM\EntityManager'
  Ads\CodeList\Ads\Ads:
    class: 'Ads\CodeList\Ads\Ports\AdsRepository'
    arguments:
      - '@Doctrine\ORM\EntityManager'
  # Slim handlers
  errors:
    public: true
    class: Ads\UI\Web\Slim\Handlers\ErrorHandler
    arguments:
    - '@Psr\Log\LoggerInterface'
    - '%app.debug%'
  # Application Logging
  Psr\Log\LoggerInterface:
    class: Monolog\Logger
    arguments:
    - 'app'
    calls:
    - method: 'pushHandler'
      arguments:
      - '@Monolog\Handler\StreamHandler'
  Monolog\Handler\StreamHandler:
    arguments:
    - '%log.path%'
    - !php/const Monolog\Logger::DEBUG
    calls:
    - method: 'pushProcessor'
      arguments:
      - '@Monolog\Processor\WebProcessor'
    - method: 'pushProcessor'
      arguments:
      - '@Monolog\Processor\UidProcessor'
    - method: 'pushProcessor'
      arguments:
      - '@Monolog\Processor\MemoryUsageProcessor'
  Monolog\Processor\WebProcessor:
  Monolog\Processor\UidProcessor:
  Monolog\Processor\MemoryUsageProcessor:
  # Command Bus
  Ads\Application\CommandBus\Bus:
    arguments:
      - '@Doctrine\ORM\EntityManager'
  # ORM
  Doctrine\ORM\EntityManager:
    factory: ['Ads\Application\DataStorage\EntityManagerFactory', 'new']
    arguments:
    - '%em.options%'
  Ads\Application\DataStorage\EntityManagerFactory:
  # JWT
  Ads\UI\Web\HTTP\JWT\TokenFactory:
    public: true
    arguments:
      - '%jwt.secret%'
  # Domain events
  Ads\Application\DomainEvents\StoredEventFactory:
    public: true
    arguments:
      - '@Ads\Application\DomainEvents\Ports\JSONSerializer'
  Ads\Application\DomainEvents\Ports\JSONSerializer:
